-- Local development mirror of the three RUNTPROD tables.
-- Column names and types transcribed from the client's DESC output.
-- Indexes mirror production, including the deliberate absence of an index
-- on AUTOMOTOR_COLOR_IDCOLOR.

SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

DROP TABLE RUNTPROD.RA_AUTOMOTOR CASCADE CONSTRAINTS;
DROP TABLE RUNTPROD.PA_COLOR CASCADE CONSTRAINTS;
DROP TABLE RUNTPROD.PA_TIPOSERVI CASCADE CONSTRAINTS;
DROP TABLE RUNTPROD.PA_MUNICPIO CASCADE CONSTRAINTS;

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE RUNTPROD.PA_COLOR (
  COLOR_IDCOLOR           NUMBER(5)      NOT NULL,
  COLOR_CODCOLMIN         VARCHAR2(5)    NOT NULL,
  COLOR_TIPOCOLOR         VARCHAR2(1),
  COLOR_PRIMARIO          VARCHAR2(200)  NOT NULL,
  COLOR_ESTADO            VARCHAR2(1)    NOT NULL,
  COLOR_GAMACOLOR_NOMBRE  VARCHAR2(50),
  CONSTRAINT PK_COLOSECUN PRIMARY KEY (COLOR_IDCOLOR)
);
CREATE INDEX RUNTPROD.IN_COLOR_PRIMARIO ON RUNTPROD.PA_COLOR (COLOR_PRIMARIO);

CREATE TABLE RUNTPROD.PA_TIPOSERVI (
  TIPOSERVI_IDETIPSER  NUMBER(3)     NOT NULL,
  TIPOSERVI_NOMBRE     VARCHAR2(300) NOT NULL,
  TIPOSERVI_ESTADO     VARCHAR2(1)   NOT NULL,
  TIPOSERVI_ANOSEXENT  NUMBER(3)     NOT NULL,
  TIPOSERVI_VIRETEME   NUMBER(3),
  TIPOSERVI_REGREPCAU  VARCHAR2(1),
  CONSTRAINT PK_TIPOSERVI PRIMARY KEY (TIPOSERVI_IDETIPSER)
);

-- Table and column names keep the client's spelling: MUNICPIO, and one
-- column spelled MUNICIPO. Correcting them would break against production.
CREATE TABLE RUNTPROD.PA_MUNICPIO (
  MUNICPIO_DIVIPOL              NUMBER(15)    NOT NULL,
  MUNICPIO_DEPARTAME_CODDPTO    NUMBER(2)     NOT NULL,
  MUNICPIO_NOMBRE               VARCHAR2(300) NOT NULL,
  MUNICPIO_REGESPADU            NUMBER(15)    NOT NULL,
  MUNICPIO_ZOREGADUA_IDREGIMEN  NUMBER(3),
  MUNICPIO_AREAMETRO_NOMBRE     VARCHAR2(30),
  MUNICIPO_REGIONMETRO_ID       NUMBER,
  CONSTRAINT PK_MUNICPIO PRIMARY KEY (MUNICPIO_DIVIPOL)
);

CREATE TABLE RUNTPROD.RA_AUTOMOTOR (
  AUTOMOTOR_NROREGVEH            NUMBER(15)   NOT NULL,
  AUTOMOTOR_PLACA_NUMPLACA       VARCHAR2(10),
  AUTOMOTOR_TIPOSERVI_IDETIPSER  NUMBER(3),
  AUTOMOTOR_CLASVEHIC_IDCLASE    NUMBER(3)    NOT NULL,
  AUTOMOTOR_COLOR_IDCOLOR        NUMBER(5),
  AUTOMOTOR_GRUPO_IDGRUPO        VARCHAR2(3),
  AUTOMOTOR_ORIGREGIS_IDEORGREG  NUMBER(3),
  AUTOMOTOR_LINEA_IDLINEA        NUMBER(10),
  AUTOMOTOR_MARCA_IDMARCA        NUMBER(10),
  AUTOMOTOR_NIVESERVI_IDNIVSER   NUMBER(3),
  AUTOMOTOR_MODASERVI_IDEMODSER  NUMBER(3),
  AUTOMOTOR_TIPOCARRO_IDCARROCE  NUMBER(5),
  AUTOMOTOR_TIPOMOTOR_IDTIPMOT   NUMBER(3),
  AUTOMOTOR_PAIS_IDPAISORI       NUMBER(3),
  AUTOMOTOR_ANOFABRIC            NUMBER(4),
  AUTOMOTOR_MODELO               NUMBER(4),
  AUTOMOTOR_ESTAREPOS            VARCHAR2(1),
  AUTOMOTOR_FECHREGIS            DATE,
  AUTOMOTOR_AUTOTRANS_IDAUTTRA   NUMBER(15),
  AUTOMOTOR_IDVEUNINT            VARCHAR2(25),
  AUTOMOTOR_IMPORTADO_NOMBRE     VARCHAR2(30),
  AUTOMOTOR_NROCHASIS            VARCHAR2(50),
  AUTOMOTOR_NROMOTOR             VARCHAR2(50),
  AUTOMOTOR_NROREGCHA            VARCHAR2(50),
  AUTOMOTOR_NROREGMOT            VARCHAR2(50),
  AUTOMOTOR_NROREGSER            VARCHAR2(50),
  AUTOMOTOR_NROSERIE             VARCHAR2(50),
  AUTOMOTOR_CILINDRAJ            NUMBER(5),
  AUTOMOTOR_ESTAVEHIC_NOMBRE     VARCHAR2(30)  NOT NULL,
  AUTOMOTOR_MOTIVO_NOMBRE        VARCHAR2(50),
  AUTOMOTOR_UNIMEDCIL_ID         NUMBER(1),
  AUTOMOTOR_REPOTENCI            VARCHAR2(1),
  AUTOMOTOR_FECHCANCE            DATE,
  AUTOMOTOR_ENSENAZA             VARCHAR2(2),
  AUTOMOTOR_MIGRADO              VARCHAR2(1),
  AUTOMOTOR_ANTICLASI_NOMBRE     VARCHAR2(10),
  AUTOMOTOR_SEGUESTAD            VARCHAR2(2),
  AUTOMOTOR_VALDOCEXI            VARCHAR2(2),
  AUTOMOTOR_FECMIGRA             DATE,
  AUTOMOTOR_FECHACTUA            DATE,
  AUTOMOTOR_PLAQUETA             VARCHAR2(10),
  AUTOMOTOR_NROREGPLA            VARCHAR2(10),
  AUTOMOTOR_TIPACTREM_NOMBRE     VARCHAR2(30),
  AUTOMOTOR_ESTAMIGR             VARCHAR2(20),
  AUTOMOTOR_NUEVMODEL            NUMBER(4),
  AUTOMOTOR_NUMCONWS             NUMBER(15),
  AUTOMOTOR_NROREGVIN            VARCHAR2(25),
  AUTOMOTOR_ANTIDECLA            VARCHAR2(25),
  AUTOMOTOR_FECACEDEC            DATE,
  AUTOMOTOR_RADIACCIO_IDRADIO    NUMBER(3),
  AUTOMOTOR_MODSEREMP_IDEMODSER  NUMBER(2),
  AUTOMOTOR_VERSION_IDVERSION    NUMBER(10),
  AUTOMOTOR_ZOREGADUA_IDREGIMEN  NUMBER(3),
  AUTOMOTOR_REGIPOSEE            VARCHAR2(1),
  AUTOMOTOR_EXTRADIME            VARCHAR2(1),
  CONSTRAINT PK_AUTOMOTOR PRIMARY KEY (AUTOMOTOR_NROREGVEH)
);

CREATE UNIQUE INDEX RUNTPROD.UQ_AUTOMOTOR_PLACA     ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_PLACA_NUMPLACA);
CREATE INDEX RUNTPROD.PLACA_NROREGVEH               ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_PLACA_NUMPLACA, AUTOMOTOR_NROREGVEH);
CREATE INDEX RUNTPROD.IDX_AUTOMOTOR_FECHREGIS       ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_FECHREGIS);
CREATE INDEX RUNTPROD.FK__AUTOMOTOR_ESTAVEHIC_16    ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_ESTAVEHIC_NOMBRE);
CREATE INDEX RUNTPROD.ESTAVEHIC_FECHCANCE           ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_ESTAVEHIC_NOMBRE, AUTOMOTOR_FECHCANCE);
CREATE INDEX RUNTPROD.FK__AUTOMOTOR_IDETIPSER_04    ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_TIPOSERVI_IDETIPSER);
CREATE INDEX RUNTPROD.FK__AUTOMOTOR_CLASVEHIC_06    ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_CLASVEHIC_IDCLASE);
CREATE INDEX RUNTPROD.FK_MOTOR_MARCA_IDMARCA        ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_MARCA_IDMARCA);
CREATE INDEX RUNTPROD.FK_MOTOR_AUTOTRANS_IDAUTTRA   ON RUNTPROD.RA_AUTOMOTOR (AUTOMOTOR_AUTOTRANS_IDAUTTRA);
-- No index on AUTOMOTOR_COLOR_IDCOLOR: matches production.

INSERT ALL
  INTO RUNTPROD.PA_COLOR VALUES (1,  'BLA', 'P', 'BLANCO',   'A', 'CLAROS')
  INTO RUNTPROD.PA_COLOR VALUES (2,  'NEG', 'P', 'NEGRO',    'A', 'OSCUROS')
  INTO RUNTPROD.PA_COLOR VALUES (3,  'GRI', 'P', 'GRIS',     'A', 'NEUTROS')
  INTO RUNTPROD.PA_COLOR VALUES (4,  'PLA', 'P', 'PLATEADO', 'A', 'NEUTROS')
  INTO RUNTPROD.PA_COLOR VALUES (5,  'ROJ', 'P', 'ROJO',     'A', 'CALIDOS')
  INTO RUNTPROD.PA_COLOR VALUES (6,  'AZU', 'P', 'AZUL',     'A', 'FRIOS')
  INTO RUNTPROD.PA_COLOR VALUES (7,  'AMA', 'P', 'AMARILLO', 'A', 'CALIDOS')
  INTO RUNTPROD.PA_COLOR VALUES (8,  'VER', 'P', 'VERDE',    'A', 'FRIOS')
  INTO RUNTPROD.PA_COLOR VALUES (9,  'BEI', 'P', 'BEIGE',    'A', 'CLAROS')
  INTO RUNTPROD.PA_COLOR VALUES (10, 'VIN', 'P', 'VINOTINTO','A', 'OSCUROS')
  INTO RUNTPROD.PA_COLOR VALUES (11, 'NAR', 'P', 'NARANJA',  'A', 'CALIDOS')
  INTO RUNTPROD.PA_COLOR VALUES (12, 'CAF', 'P', 'CAFE',     'I', 'OSCUROS')
SELECT * FROM dual;

INSERT ALL
  INTO RUNTPROD.PA_TIPOSERVI VALUES (1, 'PARTICULAR',   'A', 0, NULL, NULL)
  INTO RUNTPROD.PA_TIPOSERVI VALUES (2, 'PUBLICO',      'A', 0, NULL, NULL)
  INTO RUNTPROD.PA_TIPOSERVI VALUES (3, 'OFICIAL',      'A', 0, NULL, NULL)
  INTO RUNTPROD.PA_TIPOSERVI VALUES (4, 'DIPLOMATICO',  'A', 0, NULL, NULL)
  INTO RUNTPROD.PA_TIPOSERVI VALUES (5, 'ESPECIAL',     'A', 0, NULL, NULL)
SELECT * FROM dual;

INSERT ALL
  INTO RUNTPROD.PA_MUNICPIO VALUES (11001, 11, 'BOGOTA D.C.',  11001, NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (5001,  5,  'MEDELLIN',     5001,  NULL, 'VALLE DE ABURRA',  NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (76001, 76, 'CALI',         76001, NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (8001,  8,  'BARRANQUILLA', 8001,  NULL, 'BARRANQUILLA',     NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (13001, 13, 'CARTAGENA',    13001, NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (68001, 68, 'BUCARAMANGA',  68001, NULL, 'BUCARAMANGA',      NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (54001, 54, 'CUCUTA',       54001, NULL, 'CUCUTA',           NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (66001, 66, 'PEREIRA',      66001, NULL, 'CENTRO OCCIDENTE', NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (17001, 17, 'MANIZALES',    17001, NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (73001, 73, 'IBAGUE',       73001, NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (5400,  5,  'LA UNION',     5400,  NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (52399, 52, 'LA UNION',     52399, NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (5615,  5,  'RIONEGRO',     5615,  NULL, NULL,               NULL)
  INTO RUNTPROD.PA_MUNICPIO VALUES (68615, 68, 'RIONEGRO',     68615, NULL, NULL,               NULL)
SELECT * FROM dual;

INSERT INTO RUNTPROD.RA_AUTOMOTOR (
  AUTOMOTOR_NROREGVEH, AUTOMOTOR_PLACA_NUMPLACA, AUTOMOTOR_TIPOSERVI_IDETIPSER,
  AUTOMOTOR_CLASVEHIC_IDCLASE, AUTOMOTOR_COLOR_IDCOLOR, AUTOMOTOR_MARCA_IDMARCA,
  AUTOMOTOR_ANOFABRIC, AUTOMOTOR_MODELO, AUTOMOTOR_FECHREGIS, AUTOMOTOR_CILINDRAJ,
  AUTOMOTOR_ESTAVEHIC_NOMBRE, AUTOMOTOR_FECHCANCE, AUTOMOTOR_NROCHASIS,
  AUTOMOTOR_NROMOTOR, AUTOMOTOR_NROSERIE, AUTOMOTOR_IDVEUNINT, AUTOMOTOR_FECHACTUA,
  AUTOMOTOR_AUTOTRANS_IDAUTTRA
)
SELECT
  level,
  CHR(65 + MOD(TRUNC(level / 676000), 26)) || CHR(65 + MOD(TRUNC(level / 26000), 26)) ||
    CHR(65 + MOD(TRUNC(level / 1000), 26)) || LPAD(MOD(level, 1000), 3, '0'),
  1 + MOD(level, 5),
  1 + MOD(level, 4),
  1 + MOD(level * 3, 11),
  100 + MOD(level, 40),
  2005 + MOD(level, 21),
  2006 + MOD(level, 21),
  TRUNC(SYSDATE) - MOD(level * 17, 4000),
  CASE WHEN MOD(level, 4) = 2 THEN 125 + MOD(level, 100) ELSE 1000 + MOD(level * 11, 2600) END,
  CASE MOD(level, 20) WHEN 0 THEN 'CANCELADO' WHEN 7 THEN 'INMOVILIZADO' ELSE 'ACTIVO' END,
  CASE WHEN MOD(level, 20) = 0 THEN TRUNC(SYSDATE) - MOD(level, 900) ELSE NULL END,
  'CH' || LPAD(level, 12, '0'),
  'MT' || LPAD(level, 12, '0'),
  'SR' || LPAD(level, 12, '0'),
  'VIN' || LPAD(level, 14, '0'),
  TRUNC(SYSDATE) - MOD(level, 60),
  -- Multiplied by 7 so the municipality is not correlated with the state,
  -- which also cycles on MOD(level, 20).
  CASE
    WHEN MOD(level * 7, 20) BETWEEN 0 AND 5  THEN 11001
    WHEN MOD(level * 7, 20) BETWEEN 6 AND 8  THEN 5001
    WHEN MOD(level * 7, 20) BETWEEN 9 AND 10 THEN 76001
    WHEN MOD(level * 7, 20) BETWEEN 11 AND 12 THEN 8001
    WHEN MOD(level * 7, 20) = 13 THEN 13001
    WHEN MOD(level * 7, 20) = 14 THEN 68001
    WHEN MOD(level * 7, 20) = 15 THEN 54001
    WHEN MOD(level * 7, 20) = 16 THEN 66001
    WHEN MOD(level * 7, 20) = 17 THEN 17001
    WHEN MOD(level * 7, 20) = 18 THEN 5400
    ELSE 52399
  END
FROM dual CONNECT BY level <= 60000;

COMMIT;

BEGIN
  DBMS_STATS.GATHER_SCHEMA_STATS('RUNTPROD');
END;
/

SELECT COUNT(*) AS total_vehiculos FROM RUNTPROD.RA_AUTOMOTOR;
SELECT COUNT(*) AS amarillos_activos
  FROM RUNTPROD.RA_AUTOMOTOR
 WHERE AUTOMOTOR_COLOR_IDCOLOR = 7 AND AUTOMOTOR_ESTAVEHIC_NOMBRE = 'ACTIVO';

SELECT m.MUNICPIO_NOMBRE, COUNT(*) AS vehiculos
  FROM RUNTPROD.RA_AUTOMOTOR a
  JOIN RUNTPROD.PA_MUNICPIO m ON a.AUTOMOTOR_AUTOTRANS_IDAUTTRA = m.MUNICPIO_DIVIPOL
 GROUP BY m.MUNICPIO_NOMBRE
 ORDER BY vehiculos DESC;

EXIT
